spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka}

server:
  port: 8761

eureka:
  instance:
    hostname: ${springboot.app.name:eureka}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:eureka}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
