server:
  port: 9090

soap:
  agent:
    url: '"http://localhost:9091/ws"'

rabbitmq:
  exchange:
    comment: direct.ad.comment
    request: direct.ad.request
    search: direct.ad.search
    soap:
      ad:
        soap: direct.soap.ad.soap
  routingkey:
    comment: key.ad.comment
    request: key.ad.request
    search: key.ad.search
    soap:
      ad:
        soap: key.soap.ad.soap
  queue:
    from:
      request: queue.reques.ad # CRVENA VEZA NA SLICI
      user: queue.user.ad
    soap:
      soap:
        ad: queue.soap.soap.ad

spring:
  rabbitmq:
    host: ${RABBITMQ:localhost}
    password: guest
    username: guest
    port: 5672
  application:
    name: ${springboot.app.name:advert-manager}
  datasource:
    data: classpath:script.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    url: jdbc:mysql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:advert_manager_db}?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/4M3DMubZIrjhyUqyLC
          PjMtzxB6AHZn8dKYMSe8F78dtm9tLFZmTRoIJ5vZsoQkgoKHHVu0WcwaI+O0UXQd
          MFfNri8kkDWthlpf/2qPvs0ohC422r3hgRj1mbzFVMX4MZS6ujHgoBIe2H7xCoDR
          m4btJYUNlRSfKsumyXIYkPAJyXauquAgu9XGQl3+UX52nFl5KWpNxTDJegjEMPfY
          lWK4/zjsT/eAm2dLwIWb6fJ/Ba0B4HKXuG4uFEPU53yVUx1DUWpjCrEj3Kv55GaF
          vAZTiZlVrXMwd9JZsimxh+zJR99MLVgvnH4c43WpEh2FPjqTBqyNnqluMq9HlU74
          jwIDAQAB
          -----END PUBLIC KEY-----

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
